InsightSoftwareConsortium/ITKElastix

wrapping/itkElastixRegistrationMethod.wrap
wrapping/itkTransformixFilter.wrap

Segfault will occur running with integer pixel types.

BUG: Only wrap for real pixel types

---

include/itkElastixRegistrationMethod.hxx

Keep the default PrimaryOutput to hold the result image. There is a bug
in the ProcessObject that results in Primary and ResultImage being
duplicated in the list of outputs.

BUG: Do not use "ResultImage" for primary output

---

.gitignore
binder/requirements.txt
examples/0_HelloRegistrationWorld.ipynb
examples/1_NumPyArray.ipynb
examples/2_RegistrationParameters.ipynb

@mstaring @dzenanz @romangrothausmann please take a look.

DOC: Add registration parameters notebook

---

include/itkElastixRegistrationMethod.h
include/itkElastixRegistrationMethod.hxx

Explicitly define GetOutput() for Python wrapping without the index and
with the ResultImageType as a return type.

BUG: Define GetOutput() for Python wrapping

---

test/itkElastixRegistrationMethodTest.cxx

This is required to build with legacy disabled. Other changes are required too, but this one is easy.

COMP: use ITK_ prefix in testing macros

---

CMakeLists.txt
include/itkElastixRegistrationMethod.hxx
include/itkTransformixFilter.hxx

Removed obsolete `elastix::BaseComponent::InitializeElastixLibrary()`
calls, as Elastix is now initialized as a library by default:
"ENH: Replace InitializeElastixLibrary() by InitializeElastixExecutable()"
https://github.com/SuperElastix/elastix/pull/248
https://github.com/SuperElastix/elastix/commit/ef64fb26abcb23a21f7010b5b58f0d732431f8a8
Adjusted CMake `Elastix_LIBRARIES`, as the Elastix library CMake targets
are now named elastix_lib and transformix_lib:
"ENH: Allow building exe and lib of elastix and transformix together"
https://github.com/SuperElastix/elastix/pull/232
https://github.com/SuperElastix/elastix/commit/3944a13d8dcbe9fcc33cf348f25a1d4f59d79cd7

ENH: Switch to latest version of SuperElastix/elastix (using ITK 5.1.1)

---

wrapping/CMakeLists.txt
wrapping/transformix_extras.py

- Outputs the deformation field.
- The jacobian and it's derivative are given in a tuple, but still use disk IO, so solution is temporary, but works.

Transformix extras

---

CMakeLists.txt

Incorporates:
- https://github.com/SuperElastix/elastix/issues/355
- https://github.com/SuperElastix/elastix/pull/356

COMP: Update elastix to address macOS dangling-gsl warnings

---

.github/workflows/build-test-package.yml

For more information on the required changes, see:
- https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/pull/98
- https://github.com/InsightSoftwareConsortium/ITK/issues/2162
This has the side effect of updating ITKElastix to be based ITK 5.1.2.

COMP: Update CI for GitHub macOS runner 10.15 changes

---

.github/workflows/build-test-package.yml
CMakeLists.txt
binder/requirements.txt
setup.py
test/CMakeLists.txt
wrapping/dockcross-manylinux-build-module-wheels-opencl.sh

elastix develop branch, 2021-02-12.

ENH: Bump elastix for ITK_MODULE_TEMPLATE additions

---

examples/ITK_Example01_SimpleRegistration.ipynb
examples/ITK_Example02_CustomOrMultipleParameterMaps.ipynb
examples/ITK_Example03_Masked_3D_Registration.ipynb
examples/ITK_Example04_InitialTransformAndMultiThreading.ipynb
examples/ITK_Example05_PointRegistration.ipynb
examples/ITK_Example06_GroupwiseRegistration.ipynb
examples/ITK_Example07_MultimetricMultiImageRegistration.ipynb
examples/ITK_Example08_SimpleTransformix.ipynb
examples/ITK_Example09_PointSetAndMaskTransformation.ipynb
examples/ITK_Example10_Transformix_Jacobian.ipynb
examples/ITK_Example11_Transformix_DeformationField.ipynb
examples/ITK_Example12_DifferentSizeTransformation.ipynb
examples/ITK_UnitTestExample1_RigidRegistration.ipynb
examples/ITK_UnitTestExample2_AffineRegistration.ipynb
examples/ITK_UnitTestExample3_BsplineRegistration.ipynb
examples/ITK_UnitTestExample4_MaskedRegistration.ipynb
examples/ITK_UnitTestExample5_GroupwiseRegistration.ipynb
examples/ITK_UnitTestExample6_PointSetTransformation.ipynb
examples/ITK_UnitTestExample7_SizeTransformation.ipynb

This PR should only be merged after #102 is merged.
After that merge the notebook import statements are not necessary anymore on MacOS.
At least not for the itk-elastix functionality currently tested by the notebooks.

STYLE:Remove unnecessary notebook imports

---

.github/workflows/build-test-package.yml
examples/ITK_Example13_ITKResampling.ipynb

Updates example notebook that shows the difference in composite transform order between elastix and itk discussed in #110

DOC:Update composite transform order

---

.github/workflows/build-test-package.yml
LICENSE
README.md
examples/ITK_Example02_CustomOrMultipleParameterMaps.ipynb
examples/ITK_Example03_Masked_3D_Registration.ipynb.needtofix
examples/ITK_Example08_SimpleTransformix.ipynb
examples/ITK_Example10_Transformix_Jacobian.ipynb
examples/ITK_Example13_ITKResampling.ipynb
setup.py
test/itkElastixRegistrationMethodTest.cxx
wrapping/test/itkElastixRegistrationMethodTest.py
wrapping/test/itkTransformixFilterTest.py

- Bumps ITK dependency to `v5.3rc04.post2` tag
- Disables building Elastix with OpenMP on MacOS: xref [https://github.com/SuperElastix/elastix/issues/650](https://github.com/SuperElastix/elastix/issues/650)
- KWStyle and broken hyperlink fixes
New ITKElastix 0.14.2 packages are anticipated to address [https://github.com/InsightSoftwareConsortium/ITKElastix/issues/159](https://github.com/InsightSoftwareConsortium/ITKElastix/issues/159).

ENH: Bump ITK to v5.3rc04.post2

---

.github/workflows/build-test-package.yml
CMakeLists.txt
itk-module.cmake

Including:
pull request https://github.com/SuperElastix/elastix/pull/745
commit https://github.com/SuperElastix/elastix/commit/a3b081f58ea5c0b39cac211f510ea0fe8aad4958
"BUG: Do not try to load targets file when embedded"
by Matt McCormick (@thewtex)
pull request https://github.com/SuperElastix/elastix/pull/734
commit https://github.com/SuperElastix/elastix/commit/a640e64dc92e12e804a5caa2f634bcad1487d1aa
"BUG: Fix CL_OUT_OF_RESOURCES error"
by Konstantinos Ntatsis (@ntatsisk), with credits to @squll1peter
pull request https://github.com/SuperElastix/elastix/pull/708
commit https://github.com/SuperElastix/elastix/commit/9159c5aac9672ba31f4c88d47de5de69239dacae
"ENH: Support transforming points of Mesh objects by itk::Transformix API"

ENH: Bump elastix version to 2022-10-18 (main branch)

---

CMakeLists.txt

Including pull request https://github.com/SuperElastix/elastix/pull/747 commit https://github.com/SuperElastix/elastix/commit/89e8c5487a1fbfc6cbbf5c3a12d47af91ffd1b12
"ENH: Add `TransformixFilter::SetTransform(const TransformBase *)`"

ENH: Bump elastix version to 2022-10-26 (main branch)

---

CMakeLists.txt

Including pull request https://github.com/SuperElastix/elastix/pull/750 commit https://github.com/SuperElastix/elastix/commit/9e6efb6f9aa3b3545c7365a4b2c97aa2f88a17b5
"COMP: Use `itkSetConstObjectMacro` for TransformixFilter InputMesh"

ENH: Bump elastix version to 2022-10-29

---

examples/ITK_Example15_Transformix_image_TranslationTransform.ipynb
examples/ITK_Example16_Transformix_mesh_TranslationTransform.ipynb

Added examples on how to use recently added TransformixFilter member functions, `SetTransform`, `SetInputMesh`, and `GetOutputMesh`.

ENH: Add ipynb examples Transformix, image, mesh, TranslationTransform

---

CMakeLists.txt

Including:
pull request https://github.com/SuperElastix/elastix/pull/770
commit https://github.com/SuperElastix/elastix/commit/c0262ba1c713c0a462ada841573e3c452508da3b
"ENH: Add CMake options to not install artifacts", by Matt McCormick (@thewtex)
pull request https://github.com/SuperElastix/elastix/pull/767
"ElastixRegistrationMethod transform objects", adding:
- ElastixRegistrationMethod::GetCombinationTransform()
- TransformixFilter::SetCombinationTransform(transform)
- ElastixRegistrationMethod::GetNumberOfTransforms()
- ElastixRegistrationMethod::GetNthTransform(n)
- ElastixRegistrationMethod::ConvertToItkTransform(transform)
pull request https://github.com/SuperElastix/elastix/pull/755
commit https://github.com/SuperElastix/elastix/commit/7fe8ed9b1131e79da7b441827dce0d4abaf64544 …

ENH: Bump elastix version to 2022-12-07

---

.github/workflows/build-test-package.yml
setup.py

Features comes from the updated GitHub Action repository.

ENH: Generate Linux ARM wheels

---

.github/workflows/build-test-package.yml

Uses the macos-12 instead of macos-13 runner, which avoids sprintf warnings in the ITK build.

COMP: Update CI workflow version for sprintf warnings

---

CMakeLists.txt

elastix 5.1.0 is ~~about to be~~ [released](https://github.com/SuperElastix/elastix/releases/tag/5.1.0), this should be its final commit: https://github.com/SuperElastix/elastix/commit/d652938573e5f193955908eba225a854b31ce36a

ENH: Bump elastix version to version 5.1.0

---

examples/ITK_Example01_SimpleRegistration.ipynb

itkwidgets visualization is not currently working in MyBinder. The napari visualization does not work in MyBinder and should be updated to use the itk napari Python package to preserve spatial metadata and also point to the elastix_napari plugin. Updates for these will be tracked in separate issues.

DOC: Remove visualization section from ITK_Example01_SimpleRegistration

---

.binder/requirements.txt

I believe this was required due to bug's in numpy's typing support that have been fixed in recent versions.

COMP: Remove numpy version pin

---

.github/workflows/build-test-package.yml

Disables building for aarch64 platform in GitHub Actions. aarch64 wheel builds with emulation were taking around 7x longer than x64 wheels to build and sometimes timing out due to surpassing 6 hours total on GitHub Actions runners.
Consider re-adding support aarch64 support in the future once an immediate need is present and/or tools are improved.
Default platforms were `["_2_28-x64","2014-x64","_2_28-aarch64"]`. The input list is provided so that "_2_28-aarch64" is removed.
Motivated by discussion in #213

COMP: Disable aarch64 Python wheel builds in CI

---

CMakeLists.txt
wrapping/itkElastixRegistrationMethod.wrap
wrapping/itkTransformixFilter.wrap

Bump elastix version to 2023-05-15, including:
pull request https://github.com/SuperElastix/elastix/pull/891
commit https://github.com/SuperElastix/elastix/commit/ed15547044800c835319ac87ebc8b1e6edc0b97e
"PERF: Fill `jsj` (JacobianOfSpatialJacobian) in-place and remove `jsj1`"
pull request https://github.com/SuperElastix/elastix/pull/890
commit https://github.com/SuperElastix/elastix/commit/b9ea3a8e65a3e015a5a0f06acfb5bd22fad8dacc
"PERF: Fill `jsh` (JacobianOfSpatialJacobian) in-place and remove `jsh1`"
pull request https://github.com/SuperElastix/elastix/pull/887
commit https://github.com/SuperElastix/elastix/commit/82984859f1e6e1f9a3d53940c3b540e83c263856
PERF: Make EvaluateParzenValues calls faster, using raw buffer of values
pull request …

Bump elastix version to 2023-05-15, use C++17, support any scalar pixel type

---

.github/workflows/build-test-package.yml

Changes:
- Adds dedicated `python-build-workflow-main` job to build `itk-elastix` Python wheels for all supported Python versions on the `main` branch
- Updates `python-build-workflow-dev` to build a representative subset of `itk-elastix` experimental Python wheels for pull requests
Motivated by discussions around CI efficiency in https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/60, including @dzenanz 's proposal to test the oldest and newest supported Python versions in each PR.

PERF: Reduce Python wheel build set for GitHub CI

---

.github/workflows/build-test-package.yml

Followup to 600fcce2 disabling `python-build-workflow-dev` from running on version tag. `python-build-workflow-main` is responsible for executing full Python packaging coveraging on tags, the developer branch simply duplicates a subset of packages.
Based on duplicate pipelines running for 0.17.1:
https://github.com/InsightSoftwareConsortium/ITKElastix/actions/runs/5004635327
I do not anticipate that we will need to tag another version for these changes, but will keep an eye on the 0.17.1 CI pipelines to verify.

BUG: Avoid running development CI on tagged versions

---

.binder/requirements.txt
examples/ITK_Example09_PointSetAndMaskTransformation.ipynb
examples/ITK_Example20_PixelTypes.ipynb

itk-elastix  [`>=v0.17.0`](https://github.com/InsightSoftwareConsortium/ITKElastix/releases/tag/v0.17.0) supports any scalar pixel type. This PR:
* Adds a notebook example demonstrating this functionality.
* Updates notebook `ITK_Example09_PointSetAndMaskTransformation` to read the masks as `itk.UC` types 
EDIT: Part of the code was based on reply https://github.com/InsightSoftwareConsortium/ITKElastix/pull/211#issuecomment-1549890122 from @NHPatterson

ENH: Add/update notebooks showing the pixel type support

---

.github/workflows/build-test-package.yml

Upgraded ITKRemoteModuleBuildTestPackageAction to the latest revision from its main, from 2023-07-04. Aims to fix GitHub CI failures, especially from "cxx-build-workflow / build-test-cxx (windows-2022)".
Including:
https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/65
https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/commit/edd0a4350396f533e9ec3755ed6c5af5ddfedb97
BUG: Add missing space before closing bracket in if statements
https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/64
https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/commit/1514c2c529d3319976f82e48a9292be0297ffe9d
COMP: Do not change location when launching VS development shell
Suggested by …

COMP: Upgrade ITKRemoteModuleBuildTestPackageAction to 2023-07-04

---

.github/workflows/build-test-package.yml
setup.py

Bump CI and package dependencies for ITK v5.4 release candidate 1.
Expected to include update to C++17 build tools.

ENH: Bump for ITK v5.4rc01

---

.binder/requirements.txt

Updated the requirements for the Jupyter notebooks in ITKElastix/examples/
Suggested by Konstantinos Ntatsis (@ntatsisk).

ENH: Update required versions itk-elastix, torch, and monai in ".binder"

---

CMakeLists.txt

Including pull request https://github.com/SuperElastix/elastix/pull/944
Adds a `SetExternalInitialTransform` member function to `ElastixRegistrationMethod`, allowing to specify any ITK transform as initial transform.

ENH: Update elastix version to 2023-08-16, inc. ExternalInitialTransform

---

setup.py

Include initial transform improvements.

ENH: Bump Python package version to 0.18

---

CMakeLists.txt
setup.py

Supports passing a transform retrieved by `GetCombinationTransform()` or `GetNthTransform(n)` to `ConvertToItkTransform`, when an _external_ initial transform was specified before running the registration.
Also including various performance improvements.
Including:
pull request https://github.com/SuperElastix/elastix/pull/946
commit https://github.com/SuperElastix/elastix/commit/7bcb2b3ec7b59c85ac9f1cf1564cc90285eabb25
ENH: Write external initial transforms to ITK transform file
pull request https://github.com/SuperElastix/elastix/pull/949
commit https://github.com/SuperElastix/elastix/commit/601f4656e912cc1388fbfa4509d531b7ea5c302f
ENH: `ConvertToItkTransform` should support external initial transform
pull request https://github.com/SuperElastix/elastix/pull/950
commit …

v0.18.1: Upgrade elastix to 2023-09-18, converts external initial transforms

---

CMakeLists.txt

Set the `CMP0135` CMake policy to `NEW`: the timestamps of the
extracted files will reflect the timestamps at extraction.
Fixes:
```
CMake Warning (dev) at /Users/runner/work/_temp/-2070939391/cmake-3.24.2-macos-universal/CMake.app/Contents/share/cmake-3.24/Modules/ExternalProject.cmake:3074 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify …
```

COMP: Set `CMP0135` CMake policy to `NEW`

---

README.md

- WebAssembly CI badge
- Provides JavaScript and Python WebAssembly bindings
- Link to live JS API demo
- Wasm package installation links
- Links to Python and JavaScript wasm documentation
- Add reference to SciPy Proceedings Paper

DOC: Various README updates

---

.github/workflows/build-test-package.yml
examples/requirements.txt

Update GitHub Actions workflow to pick up `requirements.txt` for notebook testing. Also updates `requirements.txt` with missing packages.
Closes https://github.com/InsightSoftwareConsortium/ITKElastix/issues/262

BUG: Update Python requirements for notebook tests

---

.github/workflows/wasm.yml

Source:
https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian
@N-Dekker getting there 🔢

BUG: Update CI Cypress dependency installation for Ubuntu 24.04

---

.github/workflows/build-test-package.yml
pyproject.toml

Python 3.8 is officially unsupported from 2024-10-07. Python 3.9 should remain supported until October, according to https://devguide.python.org/versions/

COMP: Drop Python 3.8 (end of life)

---

wasm/python/itkwasm-elastix-emscripten/pyproject.toml
wasm/python/itkwasm-elastix-wasi/pyproject.toml
wasm/python/itkwasm-elastix/pyproject.toml

- Follow-up to https://github.com/InsightSoftwareConsortium/ITKElastix/pull/319 commit 2d237429e75b83644d6937c3c318e9a9e7bdd193
"COMP: Drop Python 3.8 (end of life)"

Remove Python 3.8 from wasm/python pyproject.toml files

---

.github/workflows/build-test-package.yml
.github/workflows/wasm.yml
pixi.lock
pnpm-lock.yaml
pyproject.toml
wasm/typescript/package.json

And itk Python dep to 5.4.2.
@N-Dekker this is a step for publishing a new Python package version. And it allows us to test recent CI configuration improvements.

ENH: Bump Python package version to 0.22.0

---

examples/ITK_Example06_GroupwiseRegistration.ipynb

Set direction matrix to the identity matrix, as a workaround for issue https://github.com/InsightSoftwareConsortium/ITKElastix/issues/291 "GroupwiseRegistration notebook: ERROR: the direction cosines matrix of the fixed image is invalid!", reported by Matt McCormick (@thewtex) on May 23, 2024.
----
@ViktorvdValk Do you remember that you saw those error messages (as reported by issue #291) when you originally made this notebook? Otherwise I wonder how the errors "sneaked in" afterwards. Could `itk.imread("data/00", itk.F)` possibly have changed _after_ you made the notebook? 🤷

BUG: Workaround "direction cosines matrix of the fixed image is invalid"

---

examples/ITK_Example_TomlFileFormatForParameterFiles.ipynb

Demonstrates TOML support for elastix registration parameter files and transformation parameter files.
---
@thewtex @mstaring @stefanklein Please have a look!

ENH: Add ITK_Example_TomlFileFormatForParameterFiles.ipynb

---

examples/ITK_Example_RegistrationWithCorrespondingPointsInMemory.ipynb

Demonstrates how to help an image registration by using a fixed and a moving set of corresponding points in memory (without file I/O).

ENH: Add ITK_Example_RegistrationWithCorrespondingPointsInMemory.ipynb

---

examples/ITK_Example_TomlFileFormatForParameterFiles.ipynb

Extended the TOML notebook, showing how to convert a Python `dict` from TOML to the elastix ParameterMap format.

ENH: Show conversion of TOML dict to elastix ParameterMap

---

CMakeLists.txt

Includes:
https://github.com/thewtex/elastix/compare/thewtex:68f3bd5...SuperElastix:fb1daee
Removes threading primative wasm workaround patches.

ENH: Bump elastix to 2025-04-08 main
