- CMakeLists.txt
> ENH: Disable KNNGraphAlphaMutualInformationMetric

- wrapping/test/CMakeLists.txt
- wrapping/test/itkElastixRegistrationMethodTest.py
> ENH: Add itkElastixRegistrationMethodTest.py

- binder/postBuild
- binder/requirements.txt
Try to avoid JupyterLab rebuilds.
> DOC: Use specific matplotlib versions on Binder

- binder/postBuild
Discussed:
https://github.com/matplotlib/jupyter-matplotlib/issues/163
> BUG: Workaround jupyter-matplotlib MyBinder versioning

- binder/postBuild
- binder/requirements.txt
For JupyterLab builds re: matplotlib/jupyter-matplotlib#163
> BUG: Require ipympl-0.4.1 in MyBinder build

- .github/workflows/build-test-package.yml
- setup.py
Adding Dask distributed support.
> ENH: Bump Python builds for v5.1.0.post3

- .github/workflows/build-test-package.yml
- setup.py
> BUG: Build against itk-5.1.1

- README.md
> DOC: add a link to Kasper's GitHub profile

- CMakeLists.txt
- wrapping/test/CMakeLists.txt
- wrapping/test/itkTransformixFilterTest.py
> ENH: Support transformix_filter functional interface

- binder/postBuild
- examples/ITK_Example01_SimpleRegistration.ipynb
- examples/ITK_Example02_CustomOrMultipleParameterMaps.ipynb
- examples/ITK_Example03_Masked_3D_Registration.ipynb
- examples/ITK_Example04_InitialTransformAndMultiThreading.ipynb
- examples/ITK_Example07_MultimetricMultiImageRegistration.ipynb
- examples/ITK_Example08_SimpleTransformix.ipynb
- examples/ITK_Example10_Transformix_Jacobian.ipynb
- examples/ITK_Example11_Transformix_DeformationField.ipynb
- examples/ITK_Example12_DifferentSizeTransformation.ipynb
- examples/ITK_UnitTestExample1_RigidRegistration.ipynb
- examples/ITK_UnitTestExample2_AffineRegistration.ipynb
- examples/ITK_UnitTestExample6_PointSetTransformation.ipynb
- Prevent errors when using 3D images in 2D notebooks examples
- Use same virtual environment for all example notebooks
- Should close issue #56
> ENH: More intuitive notebooks for 3D registration

- .github/workflows/build-test-package.yml
- setup.py
Custom tag is required for issues in the C++ builds.
Python packages have 4D support to help address #70
> ENH: Update CI build for ITK 5.2 RC 1

- setup.py
- wrapping/CMakeLists.txt
- wrapping/test/itkTransformixFilterTest.py
- wrapping/transformix_extras.py
To address failing notebook CI tests.
> BUG: Support lazing loading of the additional transformix functions

- wrapping/test/itkTransformixFilterTest.py
This PR has the transformix jacobian test uncomment as discussed in #108
> CI: Get transformix_jacobian error.

- CMakeLists.txt
Bumping the version to get latest capabilities for reading ITK transform files. It worked for me.
> ENH: update to current develop version of Elastix

- .github/workflows/notebook-test.yml
- examples/1_NumPyArray.ipynb
- examples/ITK_Example01_SimpleRegistration.ipynb
- examples/ITK_Example02_CustomOrMultipleParameterMaps.ipynb
- examples/ITK_Example03_Masked_3D_Registration.ipynb
- examples/ITK_Example04_InitialTransformAndMultiThreading.ipynb
- examples/ITK_Example05_PointRegistration.ipynb
- examples/ITK_Example06_GroupwiseRegistration.ipynb
- examples/ITK_Example07_MultimetricMultiImageRegistration.ipynb
- examples/ITK_Example09_PointSetAndMaskTransformation.ipynb
- examples/ITK_Example10_Transformix_Jacobian.ipynb
- examples/ITK_Example11_Transformix_DeformationField.ipynb
- examples/ITK_Example12_DifferentSizeTransformation.ipynb
- examples/ITK_Example13_ITKResampling.ipynb
- examples/ITK_Example14_WorldCoordinatesExplanation_Napari.ipynb
- examples/ITK_UnitTestExample1_RigidRegistration.ipynb
- examples/ITK_UnitTestExample2_AffineRegistration.ipynb
- examples/ITK_UnitTestExample3_BsplineRegistration.ipynb
- examples/ITK_UnitTestExample4_MaskedRegistration.ipynb
- examples/ITK_UnitTestExample5_GroupwiseRegistration.ipynb
- examples/ITK_UnitTestExample6_PointSetTransformation.ipynb
- examples/ITK_UnitTestExample7_SizeTransformation.ipynb
treebeard was renamed to nbmake-action.
> COMP: Update notebook CI to nbmake-action@v0.2

- setup.py
For elastix HDF5 transform improvements.
> ENH: Bump package version to 0.13.0

- .github/workflows/build-test-package.yml
- CMakeLists.txt
Followup to discussion in https://github.com/InsightSoftwareConsortium/ITKElastix/pull/173
> COMP: Disable Elastix tests by default

- .github/workflows/notebook-test.yml
- Update from nbmake-action to pytest/nbmake
- Test across platforms
> ENH: Update Notebook CI

- .github/workflows/build-test-package.yml
And prevent duplicate push/pull_request builds.
> ENH: Build Linux ARM Python packages in CI

- examples/ITK_Example04_InitialTransformAndMultiThreading.ipynb
A small fix I noticed when reading the notebooks
> Remove duplicate line of code in example notebook

- .github/workflows/wasm.yml
And upgrade build system image.
Attempt to reduce build timeouts.
> ENH: Split wasm build steps

- .github/workflows/build-test-package.yml
- Addresses issue https://github.com/InsightSoftwareConsortium/ITKElastix/issues/324
> STYLE: Shorten the names of the CI checks from build-test-package.yml
